version: '3.4'

services:
  angular-nginx:
    image: saurabhpalatkar/iot-dashboard-ui
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    command: [nginx, '-g', 'daemon off;']
  node-api:
    image: saurabhpalatkar/iot-dashboard-api
    environment:
      NODE_ENV: prod
      PORT: 3000
      MONGO_URL: mongodb://database:27017
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database      
    command: ["npm", "start"]
  database:
    image: mongo:4.0.3
    ports:
      - "27017:27017"

