version: '3.4'

services:
  angular-nginx-docker:
    container_name: ng-docker-prod-conainer
    image: ng-docker-prod-image
    build: 
      context: .
      dockerfile: prod.dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    ## set your startup file here
    command: [nginx, '-g', 'daemon off;'] 