version: "3.4"

services:
  api:
    container_name: node-api-dev-container
    image: node-api-dev-image
    build:
      context: .
      dockerfile: dev.dockerfile
    environment:
      PORT: 5000
      MONGO_URL: mongodb://database:27017
      NODE_ENV: dev
    ports:
      - "5000:5000"
    links:
      - database
    depends_on:
      - database
    command: ["npm", "start"]
  
  database:
    container_name: database-dev-container
    image: mongo:4.0.3
    ports:
      - "27017:27017"
