version: "3.4"

services:
  api:
    container_name: node-api-prod-container
    image: node-api-prod-image
    build:
      context: .
      dockerfile: prod.dockerfile
    environment:
      PORT: 3000
      MONGO_URL: mongodb://database:27017
      NODE_ENV: prod
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
    command: ["npm", "start"]
  
  database:
    container_name: database-prod-container
    image: mongo:4.0.3
    ports:
      - "27017:27017"
